# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing.

# We could also defer to the configuration for the development and test environments.
# The recommendation is that one not use role-aware application-side configuration
# files at all, except where forced to by one's frameworks (e.g. database.yml).
# See project_template/config/env-aware.yml for more info.
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:9639/solr/med" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 9639}/solr/med" %>
production:
  adapter: <%= MiddleEnglishDictionary.config.blacklight.adapter %>
  url: <%= MiddleEnglishDictionary.config.blacklight.url %>
