development:
  adapter: async

test:
  adapter: async

production:
  adapter: <%= MiddleEnglishDictionary.config.cable.adapter %>
  url: <%= MiddleEnglishDictionary.config.cable&.url %>
  channel_prefix: <%= MiddleEnglishDictionary.config.cable&.channel_prefix %>
