---
A: Anglian dialects of Old English
AE: American English
AF: Anglo-French
AL: Anglo-Latin
AN: Anglo-Norman
Ar: Arabic
Bret: Breton
Cat: Catalan
Celt: Celtic
CF: Central/Continental French
CL: Classical Latin
Corn: Cornish
Dan: Danish
Du: Dutch
E: English
EFris: East Frisian
EM: East Midland dialect of Middle English
EMnE: Early Modern English
EWS: Early West Saxon dialect of Old English
F: French
Flem: Flemish
Fris: Frisian
G: German
Gael: Gaelic
Ger: German
Gmc: Germanic
Goth: Gothic
Gr: Greek
Heb: Hebrew
HG: High German
Icel: Icelandic
Ir: Irish
It: Italian
K: Kentish dialect of Middle or Old English
L: Latin
LG: Low German
LOE: Late Old English-- 11th cent\.
LWS: Late West Saxon dialect of Old English
M: Midland dialects ofMiddle English
MDu: Middle Dutch
ME: Middle English
Merc: Mercian dialect of Old English
MFlem: Middle Flemish
MHG: Middle High German
MIr: Middle Irish
ML: Medieval Latin
ML;: Medieval Latin;
MLG: Middle Low German
MnE: Modern English
MnF: Modern French
MnG: Modern German
MnIr: Modern Irish
MnSc.Gael: Modern Scots Gaelic
MnScot: ModernScots
MScot: Middle Scots
MWel: Middle Welsh
N: Northern dialect ofMiddle English
N dial: Northern dialect of Middle English
nEM: Northeast Midland dialect of Middle English
NEM: Northeast Midland dialect of Middle English
NF: Northern French
Nhb: Northumbriandialect of Old English
NM: North Midland dialect of Middle English
Norw: Norwegian
NWM: Northwest Midland dialect of Middle English
ODan: Old Danish
OE: Old English
OF: Old French
OFris: Old Frisian
OGascon: Old Gascon
OHG: Old High German
OI: Old Icelandic
OIr: Old Irish
OIt: Old Italian
OK: Old Kentish dialect of Old English
OLFc: Old Low Franconian
'ON': Old Norse
ONF: Old Northern French
ONorw: Old Norwegian
OPic: Old Picard
OPort: Old Portuguese
OProv: Old Provencal
OS: Old Saxon
OScot: Old Scottish
OSpan: Old Spanish
OSwed: Old Swedish
OWel: Old Welsh
OWalloon: Old Walloon
Pers: Persian
Pgmc: Proto-Germanic
Pic: Picard
Port: Portuguese
Prov: Provencal
Scand: Scandinavian
Scot: Scottish
Sc.Gael: Scottish Gaelic
Sc.Gaelic: Scottish Gaelic
S: Southern dialects of Middle English except Kentish
SE: Southeastern dialect of Middle English except Kentish
SEM: Southeast Midland dialect of Middle English
Shetl: Shetland
Skt: Sanskrit
SM: South Midland dialects of Middle English
Span: Spanish
SW: Southwestern dialects of Middle English
Swed: Swedish
SWM: Southwest Midland dialect of Middle English
VL: Vulgar Latin
Vulg. L: Vulgate Latin
Wel: Welsh
WFlem: West Flemish
WGmc: West Germanic
WM: West Midland dialects of Middle English
WS: West Saxon dialect of Old English
Yks: Yorkshire
Cum: Cumberland
Dur: Durham
EMnDu: Early Modern Dutch
EMnScot: Early Modern Scots
Glo: Gloucester
LL: Late Latin
MDan: Middle Danish
MnDu: Modern Dutch
MnIcel: Modern Icelandic
MnL: Modern Latin
MnNorf: Modern Norfolk
MnNorman: Modern Norman
MnNorw: Modern Norwegian
MnYks: Modern Yorkshire
MSwed: Middle Swedish
NMidland: North Midlands
Norw.Swed: Norwegian Swedish
Nrf: Norfolk
OG: Old German
OFlem: Old Flemish
older Dan: older Danish
OLG: Old Low German
ONhb: Old Northumbrian
Suf: Suffolk
WFris: West Frisian
