db:
  url: unused

blacklight:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:9639/solr/med" %>

cable:
  adapter: async
  url: unused
  channel_prefix: dromedary

secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "somesecretkey" %>

relative_url_root: "/"
